version: 2

_cargo_cache_paths: &cargo_cache_paths
  paths:
    - "/usr/local/cargo/registry"
    - "target"

_filters_any: &filters_any
  filters:
    tags:
      only: /.*/

_filters_version_tag: &filters_version_tag
  filters:
    tags:
      only: /v[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:
  test_stable:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - test-stable-cargo-cache-{{ arch }}-{{ checksum "Cargo.toml" }}-v1
      - run: ./scripts/dev
      - run: ./scripts/test
      - save_cache:
          <<: *cargo_cache_paths
          key: test-stable-cargo-cache-{{ arch }}-{{ checksum "Cargo.toml" }}-v1

  publish:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cargo-cache-{{ arch }}-{{ checksum "Cargo.toml" }}-v1
      - run: ./scripts/publish
      - save_cache:
          <<: *cargo_cache_paths
          key: build-cargo-cache-{{ arch }}-{{ checksum "Cargo.toml" }}-v1
workflows:
  version: 2
  test_and_build:
    jobs:
      - test_stable:
          <<: *filters_any
      - publish:
          <<: *filters_version_tag
          requires:
            - test_stable
